import type { Metadata } from "next";
import { Poppins, Story_Script } from "next/font/google";
import "./globals.css";
import {Header} from "@/src/components/header/Header";
import {Sidebar} from "@/src/components/sidebar/Sidebar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  display: "swap"
});

const storyScript = Story_Script({
  variable: "--font-story",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap"
});

export const metadata: Metadata = {
  title: "Movies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${storyScript.variable} h-full antialiased`}
    >
      <body style={{ backgroundImage: "url('/images/movie-bg.webp')" }} className="min-h-full text-brand-white bg-cover bg-center bg-fixed">
        <div className="max-w-300 min-h-screen mx-auto flex flex-col">
          <Header/>
          <div className="flex flex-1 gap-0">
            <Sidebar/>
            <main className="flex-1 mt-18 bg-linear-to-r from-[#202022] via-[#212126] via-40% to-[#17171A]">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
