import type { Metadata } from "next";
import { Poppins, Story_Script } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  display: "swap"
});

const storyScript = Story_Script({
  variable: "--font-story",
  subsets: ["latin"],
  weight: ["400"],
  display: "swap"
});

export const metadata: Metadata = {
  title: "Movies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${storyScript.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" style={{ backgroundImage: "url('/images/movie-bg.webp')" }}>
        {children}
      </body>
    </html>
  );
}
